# Generated by Django 5.0.7 on 2024-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=14)),
                ('last_name', models.TextField(max_length=14)),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
    ]
